name: edtech_app
description: ""
version: 2.0.0+4
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animated_float_action_button: ^1.0.4
  auto_route: ^10.0.1
  cached_network_image: ^3.4.1
  chewie: ^1.11.0
  dio: ^5.8.0+1
  dio_smart_retry: ^7.0.1
  duration: ^4.0.3
  envied: ^1.1.1
  flash: ^3.1.1
  flex_color_scheme: ^8.2.0
  flutter:
    sdk: flutter

  flutter_displaymode: ^0.6.0
  flutter_form_builder: ^10.0.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_secure_storage_x: ^10.2.2
  flutter_svg: ^2.0.17
  form_builder_validators: ^11.1.2
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.7
  hive_ce_flutter: ^2.2.0
  hugeicons: ^0.0.10
  icons_launcher: ^3.0.1
  internet_connection_checker_plus: ^2.7.1
  intl:
  loading_animation_widget: ^1.3.0
  multiple_result: ^5.1.0
  package_rename: ^1.10.0
  path_provider: ^2.1.5
  pinput: ^5.0.1
  platform_info: ^5.0.0
  responsive_framework:
    git: https://github.com/Shreemanarjun/ResponsiveFramework.git
  slang: ^4.6.0
  slang_flutter: ^4.6.0
  talker_dio_logger: ^4.7.1
  talker_flutter: ^4.7.1
  talker_riverpod_logger: ^4.7.1
  url_launcher: ^6.3.1
  velocity_x:
  
  video_player: ^2.9.5
  webview_flutter: ^4.13.0
  youtube_player_flutter: ^9.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  riverpod_lint: ^2.6.5
  riverpod_test: ^0.1.8
  slang_build_runner: ^4.6.0
  spot: ^0.16.0
  very_good_analysis: ^7.0.0
  envied_generator: ^1.1.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/illustration/
    - assets/icon/
    - assets/app_icon/
